# Generated by Django 3.2.13 on 2023-12-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_executive_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialorganization',
            name='image',
            field=models.ImageField(default=0, upload_to='images'),
            preserve_default=False,
        ),
    ]
